### ISSUE TITLE
Change name of Color to JoltColor?

### ISSUE THREAD

**Issue by brogan89** [amerkoleci/JoltPhysicsSharp#103]
This is a bit of a nitpick suggestion, but could you change the name of `JoltPhysicsSharp.Color` to something like `JoltPhysicsSharp.JoltColor`? It clashes with `System.Drawing.Color` which is a bit annoying and need to put `using Color = System.Drawing.Color;` everywhere. 

https://github.com/amerkoleci/JoltPhysicsSharp/blob/main/src/JoltPhysicsSharp/Color.cs

**Comment by captainkidd5** [comment]
Seconding this, also an issue with Monogame/XNA Color type

**Comment by amerkoleci** [comment]
I see, need to think about this.

**Comment by captainkidd5** [comment]
Thank you!!
