### ISSUE TITLE
Add all members from Character.h

### ISSUE THREAD

**Issue by brogan89** [amerkoleci/JoltPhysicsSharp#104]
I was looking into a character controller but noticed that `Character.cs` isn't filled with all the properties, especially the essential ones like `SetLinearVelocity()`. 

I'd help adding this to the joltc lib but I'm not sure how.

https://github.com/jrouwe/JoltPhysics/blob/master/Jolt/Physics/Character/Character.h

**Comment by amerkoleci** [comment]
Hi,
I'll try to add it today, please note (as mentioned in README), any feature request would require a [sponsor](https://github.com/sponsors/amerkoleci)

Cheers,
Amer

**Comment by brogan89** [comment]
Thanks @amerkoleci. I've organized a one-off sponsor to say thanks, from [RocketWerkz](https://github.com/RocketWerkz). We may look into further sponsorships in future for any required features. We're just trialling out Jolt internally to see if it will suit our needs.

**Comment by amerkoleci** [comment]
> Thanks @amerkoleci. I've organized a one-off sponsor to say thanks, from [RocketWerkz](https://github.com/RocketWerkz). We may look into further sponsorships in future for any required features. We're just trialling out Jolt internally to see if it will suit our needs.

Hi @brogan89 
Thank you! Was trying a way to thanks RocketWerkz, really appreciated.

Feel free to reach me for any further requests or ideas.

Cheers!
