### ISSUE TITLE
Add `Character.SetShape()`

### ISSUE THREAD

**Issue by brogan89** [amerkoleci/JoltPhysicsSharp#109]
https://jrouwe.github.io/JoltPhysics/class_character.html#a15f5407b7ccbe01588462989a4e0cfda

I could get around this just slightly, but it would be much easier to add `SetShape()` to the character. 

Is there a better way to contact you as well? Email/Discord?

**Comment by amerkoleci** [comment]
Fixed with https://github.com/amerkoleci/JoltPhysicsSharp/commit/8984eca8c4a2bea1fe4798ca98b2e9831e790e1c
Grab the `2.11.1` version

Thanks!

**Comment by brogan89** [comment]
> Hi, Give me your discord handle, I'll add you there :)

My username is just `brogan` or `brogan#1282`
