### ISSUE TITLE
[Feature] Add LockX/Y/Z, Mass

### ISSUE THREAD

**Issue by MrScautHD** [amerkoleci/JoltPhysicsSharp#16]
**Could you pls add:**
+ LockX/Y/Z (To disable of a physical object to fall in a setet direction, like X).
+ Mass

I hope you can add this features :)

**Comment by amerkoleci** [comment]
Hi,
Is there something still missing? If yes can you point me to native part so I can add them?

Thanks

**Comment by MrScautHD** [comment]
No thats all 😉
