### ISSUE TITLE
[Bug] Error when build it!

### ISSUE THREAD

**Issue by MrScautHD** [amerkoleci/JoltPhysicsSharp#17]
This error comes not by every build it looks very random...

But pls take a look on it!
![Unbsafdenannt](https://github.com/amerkoleci/JoltPhysicsSharp/assets/65916181/e6845b6e-b69c-47ed-9a3f-71270933811a)

**Comment by amerkoleci** [comment]
Seams that Easel is using custom version of JoltPhysicsSharp and nuget one.

**Comment by MrScautHD** [comment]
> Seams that Easel is using custom version of JoltPhysicsSharp and nuget one.

well use not the nuget one it made a sub module
