### ISSUE TITLE
[Bug] CastRay crash the application by using it

### ISSUE THREAD

**Issue by MrScautHD** [amerkoleci/JoltPhysicsSharp#18]
Hi today i tried CastRay out and it just crash:
![grafik](https://github.com/amerkoleci/JoltPhysicsSharp/assets/65916181/60b860b8-3d32-426b-84f7-09b04b140746)

**Comment by amerkoleci** [comment]
Dude, stop spamming issues without reprocase, probably thats the fork of JoltPhysicsSharp used by Easel, the entry point is here:

https://github.com/amerkoleci/JoltPhysicsSharp/blob/main/src/joltc/joltc.h#L354

Submit PR as you can immagine those are free time side projects and I don't have infinite time.

Thanks for your attention

**Comment by MrScautHD** [comment]
> 

Easel does not effect this part, and i not take your free time or anything i just let you know that there is a bug and if you has time you should take a look on it...

**Comment by amerkoleci** [comment]
Then don't use exclamation point and help the project, if you find a problem, submit PR, you cannot just jump here and request features. 

I know it's frustrating but those are my free time projects and doesn't pay the bills 

Hope you can understand, take care :)

**Comment by MrScautHD** [comment]
I think you misunderstood me a little, it not wanna force you to fix anything... i just want to let you know.

**Comment by MrScautHD** [comment]
i saw your note, would it possible if i can donate you some money and you try to fix this bug?

**Comment by amerkoleci** [comment]
You don't have too, I wasn't mean to be offensive.

I'll fix it as soon as I have some time.

Thanks tho!
