### ISSUE TITLE
Double Precision?

### ISSUE THREAD

**Issue by MatthewBacon-Neteo** [amerkoleci/JoltPhysicsSharp#23]
Hello,

I can see the there are settings to set DoublePrecision in the JoltApi.cs but the referenced functions such as 

`
    public static extern void JPH_Body_GetPosition(IntPtr handle, out Vector3 result);
`

seem to return a single precision vector3.

is it the case that the c++ implementation supports double precision but the binding does not?

Thanks very much for the work so far.

**Comment by amerkoleci** [comment]
Thats indeed a bug, will fix it.

Thanks for spoting it

**Comment by MatthewBacon-Neteo** [comment]
Nice okay

i managed to make the changes for this single function and it seems to work nicely if i update the related classes.

```
    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void JPH_Body_GetPosition(IntPtr handle, out Vector3 result);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void JPH_Body_GetPosition(IntPtr handle, out Double3 result);
```
    
    
    I am demoing use cases at the moment, but if i stick with Jolt ill be sure to sponsor this implementation for c#.
    
    Thanks again!

**Comment by amerkoleci** [comment]
Not sure I understand, now I always use Double3 from C# and native side, whats wrong? 
you don't want the Double3 usage and want to use Vector3?

**Comment by MatthewBacon-Neteo** [comment]
Ahhh sorry for not being clear.

The master branch has this implementation:

` [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void JPH_Body_GetPosition(IntPtr handle, out Vector3 result);`

when binding to the C++ API.

Meaning that the Vector3 in c# is single precision.

I had to add 

` [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
  public static extern void JPH_Body_GetPosition(IntPtr handle, out Double3 result);`

and update the C# classes to allow access to the double precision values.

I can see in your recent commit that you are using Doubles :)

Thank you!

**Comment by amerkoleci** [comment]
Oh I see, will fix it soon, thanks!

**Comment by amerkoleci** [comment]
Version 1.7.2 uses Double3 everywhere.

Cheers!
