### ISSUE TITLE
property comparson maybe wrong

### ISSUE THREAD

**Issue by Veloctor** [amerkoleci/JoltPhysicsSharp#30]
struct MassProperties's Property: 
    public bool IsNull => Handle != 0;
    public bool IsNotNull => Handle == 0;
maybe it inverted?

**Comment by amerkoleci** [comment]
Yup, submit PR if you can, otherwise I'll fix it tomorrow. 

Thanks

**Comment by Veloctor** [comment]
I've commited pull request
