### ISSUE TITLE
set ScaleToMass doesn't work for Shape's MassProperties 

### ISSUE THREAD

**Issue by Veloctor** [amerkoleci/JoltPhysicsSharp#32]
To create a rigidbody with my destination mass, in JoltPhysics docs' method,  do following:
```
SphereShape shape = new(0.5f);
MassProperties massProperties = shape.MassProperties;
massProperties.ScaleToMass(10);
BodyCreationSettings spherSettings = new(shape, new Double3(0, 2, 0), Quaternion.Identity, MotionType.Dynamic, Layers.Moving);
Body sphereBody = bodyInterface.CreateBody(spherSettings);
Console.WriteLine("Mass: " + 1 / sphereBody.MotionProperties.InverseMassUnchecked); // not 10
```
That doesn't work.
Maybe do  `sphereBody.MotionProperties.SetMassProperties(AllowedDOFs.All, massProperties);` after that works, but what to do if I create Rigidbody with multiple Shapes with CompoundShape? there's no way to get CompoundShape's massProperties, and ConvexHullShape even have no MassProperties, so there's only one way to do that: 

```
SphereShape boxShapeForWorkAroundMass = new(1);
MassProperties createdMassProp = boxShapeForWorkAroundMass.MassProperties;
createdMassProp.ScaleToMass(128);
SphereShape shap = new(0.5f);
BodyCreationSettings spherSettings = new(shap, new Double3(0, 2, 0), Quaternion.Identity, MotionType.Dynamic, Layers.Moving);
Body sphereBody = bodyInterface.CreateBody(spherSettings);
bodyInterface.AddBody(sphereBody.ID, 0);
sphereBody.MotionProperties.SetMassProperties(AllowedDOFs.All, createdMassProp);
Console.WriteLine("Mass: " + 1 / sphereBody.MotionProperties.InverseMassUnchecked);//128
```

Maybe there's many important APIs missing?

**Comment by amerkoleci** [comment]
Not sure what is missing? can you provide a Jolt C++ example please?

**Comment by Veloctor** [comment]
> Not sure what is missing? can you provide a Jolt C++ example please?
```
	auto sphShape = new SphereShape(0.5f);
	auto boxShape = new BoxShape(Vec3{2,3,3});
	MutableCompoundShapeSettings mcssettings{};
	mcssettings.AddShape(Vec3{1,2,3},Quat::sIdentity(), sphShape);
	mcssettings.AddShape(Vec3{-1,-2,-3},Quat::sIdentity(), boxShape);
	ShapeSettings::ShapeResult sr;
	auto compound = new MutableCompoundShape{mcssettings, sr};
	auto massProp = compound->GetMassProperties();
	massProp.ScaleToMass(114514);
	BodyCreationSettings sphere_settings(compound, RVec3(0.0_r, 2.0_r, 0.0_r), Quat::sIdentity(), EMotionType::Dynamic, Layers::MOVING);
	Body* sphereBody = body_interface.CreateBody(sphere_settings);
	auto motionProp = sphereBody->GetMotionProperties();
	motionProp->SetMassProperties(EAllowedDOFs::All, massProp);
	cout << "Mass: " << 1 / motionProp->GetInverseMass() << "\tInverseInertia: " << motionProp->GetInverseInertiaDiagonal() << endl;
```

Also, I find the box MassProperties workdaround mentioned before doesn't work, because it missed angular inertia data, and I don't know why even I created a CapsuleShape(10000, 1) for Rigidbody MotionProperties override, it still has isotropic angular inertia in my test

**Comment by Mosseelight** [comment]
Ran into this same issue of the mass not being set and I think I know why. When you create a shape and set the density, the mass will change according to that density using the volume calculated. My theory why that it does not set the mass is that it will be recalculated using the density and volume, and since the density is still the same, the new mass is discarded. Got around this by creating a new shape by finding the needed density using the mass I want.
