### ISSUE TITLE
Vehicle classes missing

### ISSUE THREAD

**Issue by sowa705** [amerkoleci/JoltPhysicsSharp#37]
I cant find classes like `VehicleController ` and others. Is there a way to compile this package with the vehicle support?

**Comment by amerkoleci** [comment]
Hi,
Absolutely yes, just didn't had time to add it.
Make sure to send PR or as [README](https://github.com/amerkoleci/JoltPhysicsSharp/blob/main/README.md) states feel free to become sponsor and I'll give more priority. 

Thanks!

**Comment by jjb-pro** [comment]
Any update on this? I really need vehicle support. And by the way, thank you for your work on this project!

**Comment by amerkoleci** [comment]
Hi @jjb-pro 
As mentioned in README, any feature request would require becoming sponsor, I know lot of stuff are missing but I need to balance my free time.

Thanks!

**Comment by sowa705** [comment]
@jjb-pro switch to bepu2 physics. they actually have a complete api

**Comment by amerkoleci** [comment]
> @jjb-pro switch to bepu2 physics. they actually have a complete api

LOL, go switch to bepu2
