### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'joltc' or one of its dependencies. 

### ISSUE THREAD

**Issue by tomlister** [amerkoleci/JoltPhysicsSharp#40]
Using `dotnet run`. Can't seem to find the shared library for jolt.
OS: Macos.

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'joltc' or one of its dependencies.
```

**Comment by amerkoleci** [comment]
Hi, 
Unfortunately I don't own macos, can you try to debug this code and see how it behaves?

https://github.com/amerkoleci/JoltPhysicsSharp/blob/main/src/JoltPhysicsSharp/JoltApi.cs#L38C1-L38C1

Thanks

**Comment by Enity** [comment]
This seems to happen because "macos universal" is actually just a x64 library. without manually running it with Rosetta it won't work.

```
dlopen(...joltc.dylib, 0x0001): (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

I manually built joltc for myself (im on arm64 mac). So far everything is working, I'm testing it. maybe someday I'll make a merge request

**Comment by amerkoleci** [comment]
> This seems to happen because "macos universal" is actually just a x86 library. without manually running it with Rosetta it won't work.
> 
> ```
> dlopen(...joltc.dylib, 0x0001): (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
> ```
> 
> I manually built joltc for myself (im on arm64 mac). So far hello world example is working, I'm testing it. maybe someday I'll make a merge request (ci should build x86 and arm libs for mac)

The build builds for universal target, by using CMAKE_OSX_ARCHITECTURES it includes x64, x86 and arm64, isn't the case?

**Comment by amerkoleci** [comment]
Now it should work, I fixed it with this commit https://github.com/amerkoleci/JoltPhysicsSharp/commit/acb77a030cd1a1fb12658d2dcc6a01a68c9b5c5e 

Can you please try now? With latest native binaries

**Comment by amerkoleci** [comment]
Or grab release 2.1.2 from nuget.
