### ISSUE TITLE
Crash by starting with Debug mode (Not everytime but often)

### ISSUE THREAD

**Issue by MrScautHD** [amerkoleci/JoltPhysicsSharp#43]
Hey i try to start with debug mode and it crash often, but not everytime is kind of wierd but idk you should take a look on it.

![grafik](https://github.com/amerkoleci/JoltPhysicsSharp/assets/65916181/406525ff-16d2-46a5-ad5e-d8b401dfc2f1)

**Comment by amerkoleci** [comment]
Hi,
I need a repro case, setup an example on github and then I can try to reproduce the issue.

Thanks!

**Comment by MrScautHD** [comment]
> Hi, I need a repro case, setup an example on github and then I can try to reproduce the issue.
> 
> Thanks!

My repo: https://github.com/MrScautHD/Sparkle just run the Test project with debug mode and you see it crash

**Comment by MrScautHD** [comment]
![grafik](https://github.com/amerkoleci/JoltPhysicsSharp/assets/65916181/7ca29748-6065-42b0-b574-d45428d9b706)

**Comment by MrScautHD** [comment]
i got the problem:
By  casting double3 to vector3 it crash
![grafik](https://github.com/amerkoleci/JoltPhysicsSharp/assets/65916181/14230353-f8f2-46f7-bb11-7f51c2d02a50)

**Comment by MrScautHD** [comment]
I use this instead and this crash not the game: 
![grafik](https://github.com/amerkoleci/JoltPhysicsSharp/assets/65916181/25e7f34a-f9b8-4bb5-9504-cfe1d7a83e94)

**Comment by amerkoleci** [comment]
Thats strange because there is an explicit operator from Vector3 to Double3:

https://github.com/amerkoleci/JoltPhysicsSharp/blob/main/src/JoltPhysicsSharp/Double3.cs#L349

**Comment by MrScautHD** [comment]
sure

**Comment by MrScautHD** [comment]
intressting it looks like the bug comes back, i just started it 7 times and it is again bugy. (+ i tested your new version too nothing changed) it is maybe something else.

**Comment by MrScautHD** [comment]
In older version did that not happen i wanna see when this bug comes

**Comment by MrScautHD** [comment]
Wierd it happans everytime after a few starts

**Comment by MrScautHD** [comment]
i can not tell because i not wanna rewrite all my code but it looks like the error happans already before 2.0.0

**Comment by MrScautHD** [comment]
but it just happans on debug mode what is very wierd too

**Comment by MrScautHD** [comment]
Link to a video (to big for github):

You see it crash at the start with the Debug mode any then not anymore idk... the log tell me nothing
https://cdn.discordapp.com/attachments/1073886118027743242/1207008623373324328/2024-02-13_17-59-06.mp4?ex=65de1560&is=65cba060&hm=35b6e4369d3d07d28304be3745cdbb1bd2f5f0e8aa89ebc32480e61b0b3bdf38&

**Comment by MrScautHD** [comment]
ahh got it why it happans.

By pressing on this button, the program do not anymore run the Dispose method so it start to corrupt the memory.
![Unbenannt](https://github.com/amerkoleci/JoltPhysicsSharp/assets/65916181/7439353d-aac5-44ef-bf37-42569e3bab05)

**Comment by MrScautHD** [comment]
I'm uncertain if that qualifies as a bug, or if it's even something that can be rectified. If it's determined that it's not feasible to address, let's consider closing this issue.

**Comment by amerkoleci** [comment]
If i have repro case I would gladly fix it for you

**Comment by MrScautHD** [comment]
> If i have repro case I would gladly fix it for you

I got some news, it looks like if i wait a few seconds, minutes it start working again. Is it possible that it need some time to unload everything before running it again?

**Comment by amerkoleci** [comment]
Unload everything what? As I said I need an isolated repro case and I will try to track it

**Comment by MrScautHD** [comment]
It has the same error, you need to kill the game and instandly starting it.
![image](https://github.com/amerkoleci/JoltPhysicsSharp/assets/65916181/49bf2bfd-b34d-4f78-97e8-5219f09c7b26)

Project:
[TestJolt.zip](https://github.com/amerkoleci/JoltPhysicsSharp/files/14469151/TestJolt.zip)

**Comment by MrScautHD** [comment]
Sometimes it crash instandly so not even the debuger can tell why, but sometimes it do not crash you need to try by starting and stoping a few times by bigger projects it happans faster idk why.
![grafik](https://github.com/amerkoleci/JoltPhysicsSharp/assets/65916181/dae441bd-81b8-4a55-bd77-0ee98f86d9ff)

**Comment by MrScautHD** [comment]
Oh and btw is it normal that cubes can fall down if they to much?

![grafik](https://github.com/amerkoleci/JoltPhysicsSharp/assets/65916181/c74e608a-6c53-4937-8588-16acb01cdac7)

**Comment by amerkoleci** [comment]
> Sometimes it crash instandly so not even the debuger can tell why, but sometimes it do not crash you need to try by starting and killing a few times by bigger projects it happans faster idk why. ![grafik](https://private-user-images.githubusercontent.com/65916181/309470545-dae441bd-81b8-4a55-bd77-0ee98f86d9ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDAzNjYsIm5iZiI6MTcwOTU0MDA2NiwicGF0aCI6Ii82NTkxNjE4MS8zMDk0NzA1NDUtZGFlNDQxYmQtODFiOC00YTU1LWJkNzctMGVlOThmODZkOWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA4MTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZWQ5OTllNjZiMDViYzQxZjY2ZDI5ZDhlZGI1M2YxMjhhNTVhMWZhMGQyOTVhYmRlZmQwODc5ZDdjNGY1NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p1YMaoTCvajIll8dB-jpL6UPUPeS_H6AbLcctoTmDG8)

Hi,
I've tried and didn't experienced any crash, what should I do to reproduce the issue?

**Comment by MrScautHD** [comment]
> > Sometimes it crash instandly so not even the debuger can tell why, but sometimes it do not crash you need to try by starting and killing a few times by bigger projects it happans faster idk why. ![grafik](https://private-user-images.githubusercontent.com/65916181/309470545-dae441bd-81b8-4a55-bd77-0ee98f86d9ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDAzNjYsIm5iZiI6MTcwOTU0MDA2NiwicGF0aCI6Ii82NTkxNjE4MS8zMDk0NzA1NDUtZGFlNDQxYmQtODFiOC00YTU1LWJkNzctMGVlOThmODZkOWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA4MTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZWQ5OTllNjZiMDViYzQxZjY2ZDI5ZDhlZGI1M2YxMjhhNTVhMWZhMGQyOTVhYmRlZmQwODc5ZDdjNGY1NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p1YMaoTCvajIll8dB-jpL6UPUPeS_H6AbLcctoTmDG8)
> 
> Hi, I've tried and didn't experienced any crash, what should I do to reproduce the issue?

Mh, maybe is something wrong then with my pc.
