### ISSUE TITLE
[BUG] DllImport makes problems on some Pcs 

### ISSUE THREAD

**Issue by MrScautHD** [amerkoleci/JoltPhysicsSharp#49]
### Issue description
Hello, I'm encountering an issue with the .dll importer in C#. It's a bit puzzling because it seems to work on some PCs but not others. On my main development machine, everything runs smoothly. However, on my test PC, I consistently encounter an error. Interestingly, on my sister's PC, it works flawlessly. It's quite perplexing, but I found that replacing the .dll with the original joltc one resolves the issue on any PC.

### Issue screenshot
![image](https://github.com/amerkoleci/JoltPhysicsSharp/assets/65916181/3b491fce-544e-4f6c-ad77-b60bfb838090)

**Comment by amerkoleci** [comment]
You have own joltc.dll? In that case I cannot help, if it happens with joltc.dll from this repo I can try to help.

Try also to install visual studio 2022 C++ runtime in case

**Comment by MrScautHD** [comment]
I got some reports, here one that has a few more details:
```cs
[Sparkle.CSharp.Game :: Run] Initialize physics...
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'joltc' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/Users/artha/Downloads/Test(1)/joltc.dylib, 0x0001): tried: '/Users/artha/Downloads/Test(1)/joltc.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/artha/Downloads/Test(1)/joltc.dylib' (no such file), '/Users/artha/Downloads/Test(1)/joltc.dylib' (no such file)
dlopen(joltc.dylib, 0x0001): tried: 'joltc.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSjoltc.dylib' (no such file), '/usr/lib/joltc.dylib' (no such file, not in dyld cache), 'joltc.dylib' (no such file), '/usr/local/lib/joltc.dylib' (no such file), '/usr/lib/joltc.dylib' (no such file, not in dyld cache)
dlopen(/Users/artha/Downloads/Test(1)/libjoltc.dylib, 0x0001): tried: '/Users/artha/Downloads/Test(1)/libjoltc.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/artha/Downloads/Test(1)/libjoltc.dylib' (no such file), '/Users/artha/Downloads/Test(1)/libjoltc.dylib' (no such file)
dlopen(libjoltc.dylib, 0x0001): tried: 'libjoltc.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibjoltc.dylib' (no such file), '/usr/lib/libjoltc.dylib' (no such file, not in dyld cache), 'libjoltc.dylib' (no such file), '/usr/local/lib/libjoltc.dylib' (no such file), '/usr/lib/libjoltc.dylib' (no such file, not in dyld cache)
dlopen(/Users/artha/Downloads/Test(1)/joltc, 0x0001): tried: '/Users/artha/Downloads/Test(1)/joltc' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/artha/Downloads/Test(1)/joltc' (no such file), '/Users/artha/Downloads/Test(1)/joltc' (no such file)
dlopen(joltc, 0x0001): tried: 'joltc' (no such file), '/System/Volumes/Preboot/Cryptexes/OSjoltc' (no such file), '/usr/lib/joltc' (no such file, not in dyld cache), 'joltc' (no such file), '/usr/local/lib/joltc' (no such file), '/usr/lib/joltc' (no such file, not in dyld cache)
dlopen(/Users/artha/Downloads/Test(1)/libjoltc, 0x0001): tried: '/Users/artha/Downloads/Test(1)/libjoltc' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/artha/Downloads/Test(1)/libjoltc' (no such file), '/Users/artha/Downloads/Test(1)/libjoltc' (no such file)
dlopen(libjoltc, 0x0001): tried: 'libjoltc' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibjoltc' (no such file), '/usr/lib/libjoltc' (no such file, not in dyld cache), 'libjoltc' (no such file), '/usr/local/lib/libjoltc' (no such file), '/usr/lib/libjoltc' (no such file, not in dyld cache)

   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at JoltPhysicsSharp.JoltApi.OnDllImport(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at JoltPhysicsSharp.JoltApi.JPH_Init(UInt32 tempAllocatorSize)
   at JoltPhysicsSharp.Foundation.Init(UInt32 tempAllocatorSize, Boolean doublePrecision)
   at Sparkle.CSharp.Physics.Simulation..ctor(PhysicsSettings settings) in F:\projects\Sparkle\src\Sparkle\CSharp\Physics\Simulation.cs:line 26
   at Sparkle.CSharp.Game.Run(Scene scene) in F:\projects\Sparkle\src\Sparkle\CSharp\Game.cs:line 96
   at Program.<Main>$(String[] args) in F:\projects\Sparkle\src\Test\Program.cs:line 11
fish: Job 1, './Test' terminated by signal SIGABRT (Abort)
artha@CookieMac ~/D/Test(1) [SIGABRT]> 
```

**Comment by amerkoleci** [comment]
Can you try with latest github version?

**Comment by MrScautHD** [comment]
> Can you try with latest github version?

Sadly not, my project base on the nuget packet and if i try to compile it with the Source code (Github) i get some errors:
![grafik](https://github.com/amerkoleci/JoltPhysicsSharp/assets/65916181/94ded44e-1542-4ae1-b5fd-04da52c739b3)

**Comment by amerkoleci** [comment]
Please try with version `2.2.2` from nuget

**Comment by MrScautHD** [comment]
> Please try with version `2.2.2` from nuget

Same error

**Comment by MrScautHD** [comment]
looks like you're need to include libjoltc.dylib

![Screenshot_2024-02-08_at_21 59 29](https://github.com/amerkoleci/JoltPhysicsSharp/assets/65916181/fadc0d0b-3981-476b-9eca-52780018df8a)

**Comment by amerkoleci** [comment]
> looks like you're need to include libjoltc.dylib
> 
> ![Screenshot_2024-02-08_at_21 59 29](https://private-user-images.githubusercontent.com/65916181/303481867-fadc0d0b-3981-476b-9eca-52780018df8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MjY0MzUsIm5iZiI6MTcwNzQyNjEzNSwicGF0aCI6Ii82NTkxNjE4MS8zMDM0ODE4NjctZmFkYzBkMGItMzk4MS00NzZiLTllY2EtNTI3ODAwMThkZjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDIxMDIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZjM4ODU3ZGE3YzIwYjg1YTdkMjFmN2JlMWJiYTRlMjRiZWQzMmMyOTk0NmFiZWU0ZTcxODRmMWM0ZWM5MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wckrGAfzLtlWpv50Wn1uTSrj776Pa7dn8nDaWLOUabI)

That's should be automatically be added by .net compiler

**Comment by MrScautHD** [comment]
it do not work then

**Comment by amerkoleci** [comment]
Don't know what to do, I don't have a macos, so it's impossible for me to debug and fix the issue

**Comment by MrScautHD** [comment]
Same on happans on linux too

**Comment by MrScautHD** [comment]
ops sry nope it just happans on MacOS.

**Comment by MrScautHD** [comment]
> Don't know what to do, I don't have a macos, so it's impossible for me to debug and fix the issue 

You dont need one, just get sure the .dll get added to the build.

**Comment by amerkoleci** [comment]
Lol, feel free to fix it and submit PR

**Comment by MrScautHD** [comment]
> Lol, feel free to fix it and submit PR

Oh and it just happans for nuget if i build it with the github source code it works fine.

**Comment by MrScautHD** [comment]
Fixed
