### ISSUE TITLE
Can't find PhysicsSettings

### ISSUE THREAD

**Issue by PhilT** [amerkoleci/JoltPhysicsSharp#54]
Is there no interface to `PhysicsSettings` such as `PenetrationSlop` and `TimeBeforeSleep`?

(https://jrouwe.github.io/JoltPhysics/struct_physics_settings.html)

**Comment by amerkoleci** [comment]
Feel free to submit PR, otherwise I'll add it when I have some spare time.

**Comment by bjornbytes** [comment]
I added PhysicsSettings to the C API in #70, so now it just needs C# bindings.

**Comment by amerkoleci** [comment]
> I added PhysicsSettings to the C API in #70, so now it just needs C# bindings.

Yup, I'll handle C# side, thanks again for PR

**Comment by amerkoleci** [comment]
This was added to version 2.5.0
