### ISSUE TITLE
Null reference exception when calling GetWorldTransform(bodyID)

### ISSUE THREAD

**Issue by PhilT** [amerkoleci/JoltPhysicsSharp#57]
Not sure if this is a JoltC, Jolt C# or my own issue but calling `bodyInterface.GetWorldTransform(bodyID)` with a valid `bodyID` causes a NullReference exception. I can call other methods such as `GetRotation` or `GetPosition` and they work correctly. If it should work let me know and I'll post an example but it's not much different to the HelloWorld example just using `GetWorldTransform`.

**Comment by amerkoleci** [comment]
Hi,
I've tried in HelloWorld and no issue happens, can you reproduce a test case?

**Comment by amerkoleci** [comment]
Hi, 
I found the issue, just grab the new `2.3.3` release and tell me if it works please.

**Comment by PhilT** [comment]
That's working. Thank you so much. 

I see it's now returning an RMatrix, the double float version right.
