### ISSUE TITLE
RVec3/RMat44 use doubles even in single-precision mode

### ISSUE THREAD

**Issue by bjornbytes** [amerkoleci/JoltPhysicsSharp#58]
`JPH_RVec3` and `JPH_RMat44` are currently always defined to use doubles, even when `DOUBLE_PRECISION` option isn't set.

This causes extra float <-> double conversions:  If a user is representing their vectors as floats, they need to convert them to doubles to send them to JoltC, but JoltC will immediately convert them back to floats to send to Jolt.  These conversions aren't *that* slow, but they are unnecessary and can start to add up.

Example:

```c
void setBodyPosition(Body* body, float x, float y, float z) {
  // floats get converted to doubles here:
  JPH_RVec3 position = { x, y, z };

  // this calls ToRVec3, which converts the doubles back to floats:
  JPH_BodyInterface_SetPosition(world->body_interface, body->id, &position, JPH_Activation_Activate);
}
```

It also means that we can't operate on `RVec3`/`RMat44` as though they were arrays of floats in memory, so we need to write custom functions to convert between floats and JoltC's types instead of using e.g. memcpy or casts.

I can send a PR to change the "R" types to conditionally use floats or doubles based on the `JPH_DOUBLE_PRECISION` define, but I wanted to discuss first to make sure this sort of change would work with the C# bindings.

I don't think there are any concerns with ABI compatibility, since the library is currently set up to use different names (joltc vs. joltc_double) for the different precision modes.

**Comment by amerkoleci** [comment]
I added double precision but I'm not very satisfied by its integration, probably I would remove that part or ar least remork, so go on and send PR.

Thanks!

**Comment by amerkoleci** [comment]
Hi,
I've just handled in correct way the C layer side, commit here: https://github.com/amerkoleci/JoltPhysicsSharp/commit/6bface4bd8fd0a57723ad8c6269524e28724df21

Tell me if you have any trouble or if it works.

Thanks

**Comment by bjornbytes** [comment]
Awesome, this is working great for me, thank you!
