### ISSUE TITLE
CompoundShape is missing

### ISSUE THREAD

**Issue by skyebird189** [amerkoleci/JoltPhysicsSharp#6]
When looking at the Jolt documentation I noticed a few shapes missing, including the CompoundShape which I need for my application.

I'm going to look into adding it and creating a PR shortly but I thought I'd open an issue in case it gets added before I open a PR.

**Comment by amerkoleci** [comment]
CompoundShape added and version 1.4.1 contains them.

Cheers!

**Comment by skyebird189** [comment]
Perfect, thank you! :)
