### ISSUE TITLE
Exception when trying to create a new `CharacterVirtual` 

### ISSUE THREAD

**Issue by stanriders** [amerkoleci/JoltPhysicsSharp#76]
`var character = new CharacterVirtual(settings, new Double3(0,0,0), System.Numerics.Quaternion.Identity, 0, _physicsSystem);`
throws
`System.EntryPointNotFoundException: 'Unable to find an entry point named 'JPH_CharacterVirtual_Create' in DLL 'joltc'.'`

Library downloaded from Nuget, version 2.5.1

**Comment by amerkoleci** [comment]
Fixed in latest version, thanks!
