### ISSUE TITLE
Issue running sample with activated bodies `TempAllocator: Out of memory`

### ISSUE THREAD

**Issue by popcron** [amerkoleci/JoltPhysicsSharp#83]
hey, nice bindings library! i cloned the repo and did `dotnet run` inside the samples folder and noticed the simulation doesn't simulate due to while condition.

on this line if the sphere is created with `Activate` you get `TempAllocator: Out of memory` on the first update/step invoke:
https://github.com/amerkoleci/JoltPhysicsSharp/blob/d593bb94c08cb72ca61d26acc24ee0b144d91a64/src/samples/HelloWorld/Program.cs#L258 ![image](https://github.com/user-attachments/assets/d2084357-7f5d-4f4a-b2ff-ac5d70d1e0a6)

if instead, the while condition isnt waiting for activation and the sphere is added with `DontActivate`, then simulation can continue, but the body ofc never advances forward
![image](https://github.com/user-attachments/assets/03129b9d-71c4-4816-8210-81943dddb88d)

i then gave it `10 * 1024 * 1024` for initial temp allocator size and the same occurs sadly. i wasnt sure what i was doing wrong so i looked for other samples online and found [this](https://github.com/rodneylab/jolt-raylib-hello-world/blob/main/src/physics.cpp) familiar looking one. the sphere here is too created with `activate` flag, and i couldnt find any more info about manual activation in their docs so i deduced that adding with that flag is the correct thing to do. so are the bindings/impl version missing something or am i truly tripping on something here?

**Comment by amerkoleci** [comment]
Hi,
The "problem" was with  TempAllocatorImpl as 10 MB was not enough, the amount of memory allocated with maxBodies and others caused out of memory, now switchted to use TempAllocatorMalloc and version `2.7.1` was released on nuget.

Thanks for bringing this out
