### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by captainkidd5** [amerkoleci/JoltPhysicsSharp#91]
I'm getting a system access violation exception when attempting to access a Body.Position before or after the physics step. Any idea how I might fix this? I'm guessing it has something to do with multithreading, but I'm also not explicitly enabling multithreading anywhere, so not sure if that's something which is turned on by default?

Any idea how I can fix this?

**Comment by amerkoleci** [comment]
Hi,
As you can immagine i don't have a magic sphere and fix issues without a repro case, please share some code and I can try to help.

Thanks!
