### ISSUE TITLE
Character Virtual Inner Body Bindings

### ISSUE THREAD

**Issue by captainkidd5** [amerkoleci/JoltPhysicsSharp#92]
Are there any plans to implement Character Virtual Inner Body?

Seen [here](https://github.com/jrouwe/JoltPhysics/blob/25d3eafac60612be37094df8c92be1d90423cc1a/Jolt/Physics/Character/CharacterVirtual.h#L47)

**Comment by amerkoleci** [comment]
Fixed with https://github.com/amerkoleci/JoltPhysicsSharp/commit/428027f5208a3bf5411813c1b21bb6f57481de30
Grab the `2.9.4` version

**Comment by captainkidd5** [comment]
Fantastic work, thank you!
