### ISSUE TITLE
Pointer to unmanaged function pointer in Bindings.

### ISSUE THREAD

**Issue by Alan-FGR** [amerkoleci/JoltPhysicsSharp#96]
I noticed that in `JPH_BroadPhaseQuery_CollideAABox` , as opposed to the other similar functions there, we have a pointer type to the unmanaged function pointer:
https://github.com/amerkoleci/JoltPhysicsSharp/blob/bd2c1e2d4571a65779edc7f232a9fe8d79a4e0b2/src/JoltPhysicsSharp/JoltApi.cs#L1380
I think that star isn't supposed to be there? 😛

**Comment by amerkoleci** [comment]
Hi Alan 👋
Can you submit PR with the fix please?

Thanks dude 😀

**Comment by Alan-FGR** [comment]
Was gonna do this now. Too late 🤦‍♂️
