### ISSUE TITLE
Cast Shape Method

### ISSUE THREAD

**Issue by captainkidd5** [amerkoleci/JoltPhysicsSharp#97]
Would it be possible to create a method for shape casting which mimics the one for the ray cast, with an "out ShapeCastHitResult"?

[Here is the current one for shapecasting](https://github.com/amerkoleci/JoltPhysicsSharp/blob/3c58916afdeb7bfe84498ec234a8ced42f30e1b3/src/JoltPhysicsSharp/NarrowPhaseQuery.cs#L182)

[and here's the signature I'm looking for (but for ray casts)](https://github.com/amerkoleci/JoltPhysicsSharp/blob/3c58916afdeb7bfe84498ec234a8ced42f30e1b3/src/JoltPhysicsSharp/NarrowPhaseQuery.cs#L34)

**Comment by amerkoleci** [comment]
I'm on this, will push implementation soon.

Thanks

**Comment by captainkidd5** [comment]
Thank you!!!

**Comment by amerkoleci** [comment]
Commit: https://github.com/amerkoleci/JoltPhysicsSharp/commit/ab146b3a10819b392e7d881e5ce2bd22458e1f6a
Implements methods taking a ICollection of results and handles the internally callback logic.

Grab the `2.9.9` and tell me if it works.

Cheers,
Amer

**Comment by captainkidd5** [comment]
Thanks for working on this. Would it be possible to have it instead just spit out the ShapeCastResult?

```
public bool CastShape(Shape shape,
    in Matrix4x4 centerOfMassTransform,
    in Vector3 direction,
    in Vector3 baseOffset,
    out ShapeCastResult result, <-----------
    nint userData = 0,
    BroadPhaseLayerFilter? broadPhaseFilter = default,
    ObjectLayerFilter? objectLayerFilter = default,
    BodyFilter? bodyFilter = default,
    ShapeFilter? shapeFilter = default)
{
```

I need to reference scoped data just before calling this method which isn't accessible with a callback :/

For example, I'm looping through every X and Y grid coordinate in my Collision Grid and doing a check there, but I need to know the current X and Y in order to use the ShapeCastResult for my purpose

**Comment by captainkidd5** [comment]
Sorry for the confusion, it all works as expected!

**Comment by terinfire** [comment]
Sorry to necro-post on this.  @amerkoleci - is there a "good" way to just find all Bodies inside of a certain area?  I was considering doing this same process, but it seems a little taxing.  I'd like to supply a Bounding Box and get back all Dynamic/Kinematic Bodies within that Bounding Box?  In Bepu we had something called "GetOverlaps" on the BroadPhaseQuery, which allowed us to find everything within a volume.
