### ISSUE TITLE
Implement Get Shape

### ISSUE THREAD

**Issue by captainkidd5** [amerkoleci/JoltPhysicsSharp#99]
Hi would it be possible to implement BodyInterface.GetShape(id) and BodyInterface.GetTransformedShape(id)?

seen in the API [here](https://jrouwe.github.io/JoltPhysics/class_body_interface.html#af67cf1a0f9c7fa744d4e2387d63e04ba)

**Comment by amerkoleci** [comment]
GetShape was added, need to think about how to add GetTransformedShape

**Comment by amerkoleci** [comment]
Implemented in https://github.com/amerkoleci/JoltPhysicsSharp/commits/main/

**Comment by captainkidd5** [comment]
get shape works great, thanks a ton. Haven't had a chance to test out GetTransformedShape but i'll report back when I do
